# Generated by Django 5.0.6 on 2025-10-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('ACADEMICO', 'Academico'), ('DEPORTIVO', 'Deportivo'), ('SOCIAL', 'Social'), ('CULTURAL', 'Cultural'), ('TECNOLOGIA', 'Tecnologia')], max_length=60, unique=True),
        ),
    ]
