# Generated by Django 5.0.6 on 2025-11-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventattendee_status'),
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='visible_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this notification becomes visible/active. Used for scheduled reminders.', null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['visible_at'], name='notificatio_visible_74aa75_idx'),
        ),
    ]
