# Generated by Django 5.0.6 on 2025-12-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_visible_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INFO', 'Info'), ('REMINDER', 'Reminder'), ('ALERT', 'Alert'), ('UPDATE', 'Update')], default='INFO', max_length=60),
        ),
    ]
