<<<<<<< HEAD
# Generated by Django 5.0.6 on 2025-11-07 00:59
=======
# Generated by Django 5.0.6 on 2025-11-07 01:36
>>>>>>> c16c7c342e6446234f3ab90ad93baaa13ae76df4

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Solo debe contener letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('last_name', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Solo debe contener letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('PROFESOR', 'Profesor'), ('FUNCIONARIO', 'Funcionario'), ('EXTERNO', 'Externo')], default='EXTERNO', max_length=20)),
                ('phone', models.CharField(blank=True, error_messages={'unique': 'Ya existe un usuario con este telefono.'}, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato: "+999999999". Se permiten de 9 a 15 dígitos.', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electronico.'}, max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('cedula', models.CharField(error_messages={'unique': 'Ya existe un usuario con esta cédula.'}, max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo dígitos', regex='^\\d+$')])),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El código institucional debe contener solo dígitos', regex='^\\d*$')])),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether this user has admin privileges.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
